# Generated by Django 5.1.4 on 2025-01-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MENTES', '0004_diagnose_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='predict_diagnose',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
