# Generated by Django 5.1.4 on 2025-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_age_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Enter your medical history', null=True),
        ),
    ]
